### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by bsmith8108**
Needed updates to README, help any users understand what is going on

### CODE REVIEW

**Review by gpsmith8108 — CHANGES_REQUESTED** [review]
You should make better contributions

**Comment by gpsmith8108** [comment]
can you see this brandon?

**Review by gpsmith8108 — APPROVED** [review]

**Comment by bsmith8108** [comment]
I can and I appreciate you finally recognizing the genius of my contributions

**Comment by bsmith8108** [comment]
I don't see it merged though?

**Review by gpsmith8108 — APPROVED** [review]

**Comment by gpsmith8108** [comment]
I don't know why your contributions didnt stick, but I updated the READme

**Pull request closed without merging**
